name:                arch-zfs-iso-test
version:             0.1.0.0

dependencies:
- base
- containers
- directory
- filepath
- hslogger
- process
- temporary
- text

executables:
  arch-zfs-iso-test:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
